### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by LuisTS** [Gyvastis/nudity-detector-api#2]
Hello,
I want to use nudity-detector-api in my project. I've downloaded your code and I see that you are using this URL for image checking:

http://www.nudedetect.com/process.php?url=http://www.sample.com/image

But if I enter Mashape market (https://market.mashape.com/netspark/nude-detect) I've found that you must subscribe and provide a account card number for using the API, even if you select the free basic mode.

I would like to know if your API callings has any usage limit, and how I can check it.  

Thanks.

**Comment by Gyvastis** [comment]
Yes, I use their "Test Now!" functionality, so it cannot be tested for limits or reliability for that matter, though I doubt they monitor it. My code should only be used as a temporary service before you find a permanent one or if you have an MVP version of your project and you want to save up for now.

**Comment by LuisTS** [comment]
Thanks Vaidas, for now I will seek another API as an alternative.
My project is not a MVP version and i can not risk.
See you!
